# Generated by Django 5.1.4 on 2024-12-08 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=65, verbose_name='nombre')),
                ('telefono', models.CharField(max_length=9, verbose_name='telefono')),
                ('correo', models.EmailField(max_length=256)),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion')),
                ('tipo', models.CharField(choices=[('regular', 'regular'), ('premium', 'premium')], max_length=7, verbose_name='tipo CLiente')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=65, verbose_name='nombre')),
                ('especie', models.CharField(max_length=65, verbose_name='especie')),
                ('raza', models.CharField(max_length=65, verbose_name='raza')),
                ('edad', models.IntegerField(verbose_name='edad')),
                ('peso', models.FloatField(verbose_name='edad')),
            ],
            options={
                'db_table': 'mascotas',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=65, verbose_name='nombre')),
                ('tipo', models.CharField(max_length=100, verbose_name='tipo')),
                ('dosis', models.CharField(max_length=100, verbose_name='dosis')),
                ('cantidad', models.IntegerField(verbose_name='stock')),
            ],
            options={
                'db_table': 'medicamnentos',
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=65, verbose_name='nombre')),
                ('especialidad', models.CharField(max_length=100, verbose_name='especialidad')),
                ('horarios', models.CharField(max_length=100, verbose_name='horarios')),
                ('estado', models.CharField(choices=[('Disponible', 'disponible'), ('Ocupadp', 'ocupado')], max_length=11, verbose_name='estadio')),
            ],
            options={
                'db_table': 'veterinarios',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('motivo', models.TextField(verbose_name='motivo consulta')),
                ('diagnostico', models.CharField(max_length=100, verbose_name='diagnostico')),
                ('tratamiento', models.CharField(max_length=200, verbose_name='tratamiento')),
                ('estado', models.CharField(choices=[('Disponible', 'disponible'), ('Ocupadp', 'ocupado')], max_length=11, verbose_name='estadio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mascota')),
            ],
            options={
                'db_table': 'consultas',
            },
        ),
    ]
