# Generated by Django 5.1.4 on 2024-12-08 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='cliente',
        ),
        migrations.AddField(
            model_name='consulta',
            name='veterinario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.veterinario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'disponible'), ('Ocupadp', 'ocupado')], max_length=11, verbose_name='estado'),
        ),
    ]
